(() => {
  if(window.__tmIncomeReviewLoaded)return;window.__tmIncomeReviewLoaded=true;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=v=>typeof money==='function'?money(v):new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(+v||0);
  const n=v=>+v||0;
  function popup(title,body,footer=''){document.querySelector('.tm-overlay')?.remove();const o=document.createElement('div');o.className='tm-overlay';o.innerHTML=`<div class="tm-pop"><div class="tm-pop-h"><h3>${title}</h3><button class="tm-close" type="button">×</button></div><div class="tm-pop-b">${body}</div>${footer?`<div class="tm-pop-f">${footer}</div>`:''}</div>`;o.querySelector('.tm-close').onclick=()=>o.remove();o.addEventListener('click',e=>{if(e.target===o)o.remove()});document.body.appendChild(o);return o;}
  function toast(msg){let x=document.getElementById('tm-review-toast');if(!x){x=document.createElement('div');x.id='tm-review-toast';x.style.cssText='position:fixed;right:22px;top:22px;z-index:99999;background:#173f69;color:#fff;padding:13px 16px;border-radius:12px;font-weight:800;box-shadow:0 12px 28px rgba(0,0,0,.2)';document.body.appendChild(x)}x.textContent=msg;x.style.display='block';clearTimeout(x._t);x._t=setTimeout(()=>x.style.display='none',3000)}
  window.tmOpenIncomeReview=function(id){
    const r=(S.r||[]).find(x=>String(x.id)===String(id));if(!r)return alert('No encontré este ingreso.');
    const b=r.breakdown||{};
    const o=popup(`Revisión de ingreso · ${esc(r.invoice||'')}`,`<div class="tm-kpis"><div class="tm-kpi"><small>Cliente</small><b style="font-size:16px">${esc(r.client||'')}</b></div><div class="tm-kpi"><small>Pago recibido</small><b>${fmt(r.gross)}</b></div><div class="tm-kpi"><small>Factura</small><b style="font-size:16px">${esc(r.invoice||'')}</b></div><div class="tm-kpi"><small>Estado</small><b style="font-size:16px">${r.reviewStatus==='Revisado'?'Revisado':'Por revisar'}</b></div></div><div class="section">Desglose del pago</div><div class="tm-grid"><div class="tm-field"><label>Down payment / Prima</label><input id="rvPrima" type="number" min="0" step="0.01" value="${n(b.prima)}"></div><div class="tm-field"><label>Fee de agencia</label><input id="rvFee" type="number" min="0" step="0.01" value="${n(b.fee)}"></div><div class="tm-field"><label>Comisión</label><input id="rvCommission" type="number" min="0" step="0.01" value="${n(b.commission)}"></div><div class="tm-field"><label>Otro</label><input id="rvOther" type="number" min="0" step="0.01" value="${n(b.other)}"></div></div><div class="tm-note" id="rvTotal" style="margin-top:12px;font-weight:800"></div><div class="tm-note">El Fee procesador de Stripe no forma parte de este desglose.</div>`,`<button class="btn soft" id="rvCancel">Cancelar</button><button class="btn navy" id="rvSave">Guardar revisión</button>`);
    const ids=['rvPrima','rvFee','rvCommission','rvOther'];const total=()=>ids.reduce((a,id2)=>a+n(o.querySelector('#'+id2).value),0);const paint=()=>{const t=total(),ok=Math.abs(t-n(r.gross))<.01;o.querySelector('#rvTotal').textContent=`Total clasificado: ${fmt(t)} / ${fmt(r.gross)} ${ok?'✓':''}`;o.querySelector('#rvTotal').style.color=ok?'#16754c':'#a72f43'};ids.forEach(id2=>o.querySelector('#'+id2).oninput=paint);paint();
    o.querySelector('#rvCancel').onclick=()=>o.remove();o.querySelector('#rvSave').onclick=()=>{const t=total();if(Math.abs(t-n(r.gross))>.01)return alert('El total clasificado debe ser igual al pago recibido.');r.breakdown={prima:n(o.querySelector('#rvPrima').value),fee:n(o.querySelector('#rvFee').value),commission:n(o.querySelector('#rvCommission').value),other:n(o.querySelector('#rvOther').value)};r.reviewStatus='Revisado';r.incomeType='Desglosado';(S.t||[]).forEach(tk=>{if(tk.reviewInvoice===r.invoice&&!tk.done){tk.done=true;tk.status='Realizada';tk.doneAt=new Date().toISOString().slice(0,10)}});store();o.remove();toast('Ingreso revisado correctamente.');setTimeout(()=>{try{render()}catch(_){}},80)};
  };
})();